In [1]:
3+5


8

In [1]:
import numpy as np 
v = np . array ( [ 1 , 2 ] )

In [2]:
a = np . array ( [ [ 1 , 2 , 3] , [4 , 5 , 6 ] ] ) 
a . ndim 

2

In [3]:
a . shape

(2, 3)

In [4]:
a . size 

6

In [5]:
 a.dtype

dtype('int32')

In [6]:
b = np . array ( [ [ 1.0 , 2.0 , 3.0] , [4.0 , 5.0 , 6.0 ] ] ) 

In [7]:
b.dtype

dtype('float64')

In [13]:
 a = np.array(range(10), float)
 a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
a.dtype

dtype('float64')

In [12]:
v = np . arange ( -1.0,1.0 , 0.2 )
v

array([-1.00000000e+00, -8.00000000e-01, -6.00000000e-01, -4.00000000e-01,
       -2.00000000e-01, -2.22044605e-16,  2.00000000e-01,  4.00000000e-01,
        6.00000000e-01,  8.00000000e-01])

In [15]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.linspace(0, 2, 9) 


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [19]:
a = np . fromfunction ( lambda i , j : i == j , (3 , 3) ) 
a

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [20]:
a = np . arange ( 6 )
a

array([0, 1, 2, 3, 4, 5])

In [21]:
b = np . reshape ( a , (3 , 2) ) 
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [22]:
b[0,0]=9

In [23]:
a
b

array([[9, 1],
       [2, 3],
       [4, 5]])

In [24]:
a


array([9, 1, 2, 3, 4, 5])

In [25]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
x+y

array([[ 6.,  8.],
       [10., 12.]])

In [30]:
a = np.reshape ( np.arange ( 6 ) , (2 , -1) ) 
print(a/(a +1) )

[[0.         0.5        0.66666667]
 [0.75       0.8        0.83333333]]


In [31]:
np.random.sample()

0.026982252420388764

In [34]:
array=np.random.randint(0, 3, 10)
array

array([1, 2, 0, 1, 2, 1, 2, 1, 2, 0])

In [33]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c