In [1]:
3+5


8

In [1]:
import numpy as np 
v = np . array ( [ 1 , 2 ] )

In [2]:
a = np . array ( [ [ 1 , 2 , 3] , [4 , 5 , 6 ] ] ) 
a . ndim 

2

In [3]:
a . shape

(2, 3)

In [4]:
a . size 

6

In [5]:
 a.dtype

dtype('int32')

In [6]:
b = np . array ( [ [ 1.0 , 2.0 , 3.0] , [4.0 , 5.0 , 6.0 ] ] ) 

In [7]:
b.dtype

dtype('float64')

In [13]:
 a = np.array(range(10), float)
 a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
a.dtype

dtype('float64')

In [12]:
v = np . arange ( -1.0,1.0 , 0.2 )
v

array([-1.00000000e+00, -8.00000000e-01, -6.00000000e-01, -4.00000000e-01,
       -2.00000000e-01, -2.22044605e-16,  2.00000000e-01,  4.00000000e-01,
        6.00000000e-01,  8.00000000e-01])

In [15]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.linspace(0, 2, 9) 


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])