In [1]:
import numpy as np 

In [5]:
 np.arange(5, dtype=float)
 a

array([0., 1., 2., 3., 4.])

In [4]:
 a = np.array(range(5), float)
a

array([0., 1., 2., 3., 4.])

In [6]:
 np.arange(1, 6, 2, dtype=int)

array([1, 3, 5])

In [7]:
np.ones((2,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.zeros(7, dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

In [11]:
 a = np.array([[1, 2, 3], [4, 5, 6]], float)
a


array([[1., 2., 3.],
       [4., 5., 6.]])

In [12]:
np.zeros_like(a)


array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
 np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.identity(4, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
 np.eye(4, k=2, dtype=float)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
a = np.array([1,2,3], float)
a

array([1., 2., 3.])

In [20]:
b = np.array([5,2,6], float)
b

array([5., 2., 6.])

In [21]:
a+b

array([6., 4., 9.])

In [22]:
a-b

array([-4.,  0., -3.])

In [23]:
a * b

array([ 5.,  4., 18.])

In [24]:
 b / a

array([5., 1., 2.])

In [25]:
a % b

array([1., 0., 3.])

In [26]:
b**a

array([  5.,   4., 216.])

In [28]:
a = np.array([[1,2], [3,4]], float)
a

array([[1., 2.],
       [3., 4.]])

In [29]:
b = np.array([[2,0], [1,3]], float)
b

array([[2., 0.],
       [1., 3.]])

In [30]:
 a * b

array([[ 2.,  0.],
       [ 3., 12.]])

In [31]:
c=np.dot(a,b)
c

array([[ 4.,  6.],
       [10., 12.]])

In [32]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [33]:
b = np.array([-1, 3], float)
b

array([-1.,  3.])

In [34]:
a + b


array([[0., 5.],
       [2., 7.],
       [4., 9.]])

In [35]:
a = np.zeros((2,2), float)
a

array([[0., 0.],
       [0., 0.]])

In [36]:
 b = np.array([-1., 3.], float)
b

array([-1.,  3.])

In [37]:
a + b

array([[-1.,  3.],
       [-1.,  3.]])

In [38]:
a + b[np.newaxis,:]

array([[-1.,  3.],
       [-1.,  3.]])

In [39]:
 a + b[:,np.newaxis]

array([[-1., -1.],
       [ 3.,  3.]])

In [42]:
 a = np.array([1, 4, 9], float)
 a

array([1., 4., 9.])

In [43]:
np.sqrt(a)

array([1., 2., 3.])

In [44]:
 a = np.array([1.1, 1.5, 1.9], float)
 a

array([1.1, 1.5, 1.9])

In [45]:
np.floor(a)

array([1., 1., 1.])

In [46]:
np.pi

3.141592653589793

In [47]:
 a = np.array([1, 4, 5], int)
 a

array([1, 4, 5])

In [49]:
 for x in a:
       print(x)

1
4
5


In [50]:
 a = np.array([[1, 2], [3, 4], [5, 6]], float)
 a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [51]:
 for x in a:
       print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [52]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)

In [53]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [54]:
for (x, y) in a:
    print(x*y)

2.0
12.0
30.0


In [55]:
a = np.array([2, 4, 3], float)
a


array([2., 4., 3.])

In [56]:
a.sum()

9.0

In [57]:
a.prod()

24.0

In [58]:
a.mean()

3.0

In [59]:
a.var()

0.6666666666666666

In [60]:
a.argmin()

0

In [61]:
a = np.array([[0, 2], [3, -1], [3, 5]], float)
a

array([[ 0.,  2.],
       [ 3., -1.],
       [ 3.,  5.]])

In [62]:
a.mean(axis=0)


array([2., 2.])

In [63]:
 a.mean(axis=1)
    

array([1., 1., 4.])

In [64]:
 a.max(axis=0)

array([3., 5.])

In [65]:
a = np.array([6, 2, 5, -1, 0], float)
a


array([ 6.,  2.,  5., -1.,  0.])

In [66]:
sorted(a)

[-1.0, 0.0, 2.0, 5.0, 6.0]

In [67]:
 a.sort()

In [68]:
a

array([-1.,  0.,  2.,  5.,  6.])

In [69]:
 a = np.array([6, 2, 5, -1, 0], float)
 a

array([ 6.,  2.,  5., -1.,  0.])

In [70]:
a.clip(0, 5)

array([5., 2., 5., 0., 0.])

In [71]:
a = np.array([1, 1, 4, 5, 5, 5, 7], float)

In [72]:
a

array([1., 1., 4., 5., 5., 5., 7.])

In [73]:
np.unique(a)

array([1., 4., 5., 7.])

In [74]:
 a = np.array([[1, 2], [3, 4]], float)
a

array([[1., 2.],
       [3., 4.]])

In [75]:
a.diagonal()

array([1., 4.])