In [1]:
import numpy as np 

In [2]:
 a = np.array([1, 3, 0], float)

In [3]:
b = np.array([0, 3, 2], float)

In [4]:
a > b

array([ True, False, False])

In [5]:
 a == b

array([False,  True, False])

In [6]:
 c = a > b
c

array([ True, False, False])

In [7]:
a>2

array([False,  True, False])

In [10]:
 c = np.array([ True, False, False], bool)
c

array([ True, False, False])

In [11]:
any(c)

True

In [12]:
all(c)

False

In [18]:
 a = np.array([1, 3, 0], float)
a

array([1., 3., 0.])

In [22]:
 np.logical_and(a >= 0, a < 3)

array([ True, False,  True])

In [14]:
b = np.array([True, False, True], bool)
b

array([ True, False,  True])

In [15]:
np.logical_not(b)

array([False,  True, False])

In [16]:
 c = np.array([False, True, False], bool)

In [17]:
c

array([False,  True, False])

In [23]:
 a = np.array([1, 3, 0], float)
a

array([1., 3., 0.])

In [24]:
np.where(a != 0, 1 / a, a)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([1.        , 0.33333333, 0.        ])

In [25]:
np.where(a == 1, 1 / a, a)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([1., 3., 0.])

In [26]:
np.where(a != 1, 1 / a, a)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([1.        , 0.33333333,        inf])

In [29]:
 np.where(a > 0, 100, 2)

array([100, 100,   2])

In [28]:
a

array([1., 3., 0.])

In [30]:
 a = np.array([[0, 1], [3, 0]], float)

In [31]:
a

array([[0., 1.],
       [3., 0.]])

In [32]:
a.nonzero()

(array([0, 1], dtype=int64), array([1, 0], dtype=int64))

In [33]:
a = np.array([1, np.NaN, np.Inf], float)

In [34]:
a

array([ 1., nan, inf])

In [35]:
np.isnan(a)

array([False,  True, False])

In [36]:
np.isfinite(a)

array([ True, False, False])

In [37]:
a = np.array([[6, 4], [5, 9]], float)

In [38]:
a

array([[6., 4.],
       [5., 9.]])

In [39]:
 a >= 6

array([[ True, False],
       [False,  True]])

In [40]:
a[a >= 6]

array([6., 9.])

In [41]:
sel = (a >= 6)

In [42]:
a[sel]

array([6., 9.])

In [43]:
a[np.logical_and(a > 5, a < 9)]

array([6.])

In [44]:
np.logical_and(a > 5, a < 9)

array([[ True, False],
       [False, False]])

In [45]:
a = np.array([2, 4, 6, 8], float)

In [46]:
a

array([2., 4., 6., 8.])

In [47]:
b = np.array([0, 0, 1, 3, 2, 1], int)
b

array([0, 0, 1, 3, 2, 1])

In [48]:
 a[b]

array([2., 2., 4., 8., 6., 4.])

In [49]:
 a = np.array([[1, 4], [9, 16]], float)

In [50]:
a

array([[ 1.,  4.],
       [ 9., 16.]])

In [51]:
b = np.array([0, 0, 1, 1, 0], int)

In [52]:
b

array([0, 0, 1, 1, 0])

In [53]:
 c = np.array([0, 1, 1, 1, 1], int)

In [54]:
c

array([0, 1, 1, 1, 1])

In [55]:
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

In [56]:
 a = np.array([2, 4, 6, 8], float)

In [57]:
a

array([2., 4., 6., 8.])

In [59]:
 b = np.array([0, 0, 1, 3, 2, 1], int)
 b

array([0, 0, 1, 3, 2, 1])

In [60]:
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [61]:
a = np.array([[0, 1], [2, 3]], float)

In [62]:
a


array([[0., 1.],
       [2., 3.]])

In [63]:
b = np.array([0, 0, 1], int)
b

array([0, 0, 1])

In [64]:
a.take(b, axis=0)

array([[0., 1.],
       [0., 1.],
       [2., 3.]])

In [65]:
 a.take(b, axis=1)

array([[0., 0., 1.],
       [2., 2., 3.]])

In [66]:
 a = np.array([0, 1, 2, 3, 4, 5], float)
a

array([0., 1., 2., 3., 4., 5.])

In [67]:
b = np.array([9, 8, 7], float)

In [68]:
b


array([9., 8., 7.])

In [69]:
a.put([0, 3], b)

In [70]:
a

array([9., 1., 2., 8., 4., 5.])