In [1]:
import numpy as np 

In [2]:
a = np.array([1, 2, 3], float)
a

array([1., 2., 3.])

In [3]:
b = np.array([0, 1, 1], float)
b


array([0., 1., 1.])

In [4]:
np.dot(a, b)

5.0

In [5]:
 a = np.array([1, 4, 0], float)
a

array([1., 4., 0.])

In [6]:
b = np.array([2, 2, 1], float)
b

array([2., 2., 1.])

In [7]:
np.outer(a, b)

array([[2., 2., 1.],
       [8., 8., 4.],
       [0., 0., 0.]])

In [8]:
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], float)
a

array([[4., 2., 0.],
       [9., 3., 7.],
       [1., 2., 1.]])

In [9]:
 np.linalg.det(a)

-48.00000000000003

In [10]:
 vals, vecs = np.linalg.eig(a)

In [11]:
vals


array([ 8.85591316,  1.9391628 , -2.79507597])

In [12]:
vecs

array([[-0.3663565 , -0.54736745,  0.25928158],
       [-0.88949768,  0.5640176 , -0.88091903],
       [-0.27308752,  0.61828231,  0.39592263]])

In [13]:
 b = np.linalg.inv(a)

In [14]:
b

array([[ 0.22916667,  0.04166667, -0.29166667],
       [ 0.04166667, -0.08333333,  0.58333333],
       [-0.3125    ,  0.125     ,  0.125     ]])

In [15]:
np.dot(a, b)

array([[1.00000000e+00, 5.55111512e-17, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 2.22044605e-16],
       [0.00000000e+00, 1.38777878e-17, 1.00000000e+00]])

In [16]:
 np.poly([-1, 1, 1, 10])

array([  1., -11.,   9.,  11., -10.])

In [17]:
np.roots([1, 4, -2, 3])

array([-4.5797401 +0.j        ,  0.28987005+0.75566815j,
        0.28987005-0.75566815j])

In [18]:
 a = np.array([1, 4, 3, 8, 9, 2, 3], float)

In [19]:
a


array([1., 4., 3., 8., 9., 2., 3.])

In [20]:
np.median(a)

3.0

In [21]:
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float)

In [22]:
a

array([[1., 2., 1., 3.],
       [5., 3., 1., 8.]])

In [23]:
c = np.corrcoef(a)

In [24]:
c

array([[1.        , 0.72870505],
       [0.72870505, 1.        ]])

In [25]:
np.cov(a)


array([[0.91666667, 2.08333333],
       [2.08333333, 8.91666667]])

In [26]:
 np.random.seed(293423)

In [27]:
 np.random.rand(5)

array([0.33677247, 0.52693437, 0.79529578, 0.78867702, 0.02147624])

In [28]:
np.random.rand(2,3)

array([[0.84612516, 0.0704939 , 0.1526965 ],
       [0.77831701, 0.80821151, 0.82198398]])

In [29]:
np.random.rand(6).reshape((2,3))

array([[0.90239653, 0.8385685 , 0.02638565],
       [0.33681448, 0.46480928, 0.61686496]])

In [30]:
 np.random.random()

0.43767262538051455

In [31]:
np.random.randint(5, 10)

5

In [32]:
np.random.poisson(6.0)

4

In [33]:
 np.random.normal(1.5, 4.0)

-1.5224080889736675

In [34]:
 np.random.normal()

0.957100788846741

In [35]:
np.random.normal(size=5)

array([-1.01092541,  0.58092445,  1.122653  , -0.1252049 ,  0.57716007])

In [36]:
l = range(10)

In [37]:
l

range(0, 10)

In [38]:
np.random.shuffle(l)

TypeError: 'range' object does not support item assignment

In [40]:
l = range(10)
l

range(0, 10)

In [41]:
 a = np.array(range(10), float)

In [42]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
np.random.shuffle(a)

In [44]:
a

array([0., 2., 3., 9., 5., 7., 1., 4., 8., 6.])